name: Check terraform file formatting and format
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.hcl'
      - '**.yml'
  workflow_dispatch:
    inputs:
      subcommand:
        type: string
        required: true
        description: 'terragrunt subcommand'
jobs:
  format:
    runs-on: ubuntu-20.04
    name: Check terraform file are formatted correctly
    steps:
      - name: Terragrunt GitHub Actions
        # uses: the-commons-project/terragrunt-github-actions@1.0.6
        run: echo ${{ github.event.inputs.subcommand }}

