name: Check terraform file formatting and format
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.hcl'
      - '**.yml'
env:
  tf_actions_version: 1.3.6
  tg_actions_version: 0.39.2
  tf_actions_working_dir: terraform/environment/dev
jobs:
  format:
    runs-on: ubuntu-20.04
    name: Check terraform file are formatted correctly
    steps:
      - name: Terragrunt GitHub Actions
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
            tf_actions_version: 1.3.6
            tg_actions_version: 0.39.2
            tf_actions_subcommand: run-all fmt
            tf_actions_working_dir: terraform/environment/dev
          
        

