name: Check terraform file formatting and format
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.hcl'
      - '**.yml'
env:
  INPUT_TF_ACTIONS_SUBCOMMAND: plan
jobs:
  format:
    runs-on: ubuntu-20.04
    name: Check terraform file are formatted correctly
    steps:
      - name: Terragrunt GitHub Actions
        uses: the-commons-project/terragrunt-github-actions@1.0.6

